variables:
  APP_CONTAINER_PORT: "80"
  APP_EXPOSED_PORT: "80"

image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - Build
  - Test acceptation
  - Release image
  - Deploy staging
  - Test staging
  - Deploy review
  - Stop review
  - Deploy prod
  - Test prod

.test_template: &test
  image: alpine
  only:
    - main
  script:
    - apk --no-cache add curl
    - echo $DOMAIN
    - curl "https://$DOMAIN" | grep -i "Dimension"  

docker-build:
  stage: Build
  script:
    - docker build -t  mini_projet_gitlab .
    - docker save mini_projet_gitlab > mini_projet_gitlab.tar
  artifacts:
    paths:
      - mini_projet_gitlab.tar

test acceptation:
  stage: Test acceptation
  script:
    - docker load < mini_projet_gitlab.tar
    - docker run -d -p $APP_CONTAINER_PORT:$APP_EXPOSED_PORT -e PORT=$APP_CONTAINER_PORT --name webapp mini_projet_gitlab
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker:$APP_CONTAINER_PORT" | grep -i "Dimension"

release image:
  stage: Release image
  script:
    - echo ${IMAGE_NAME}
    - docker load < mini_projet_gitlab.tar
    - docker tag mini_projet_gitlab "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag mini_projet_gitlab "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: https://mini-projet-gitlab-staging-aug-4cf9ddbae0fe.herokuapp.com/
  only:
    - staging
  script:
    - apk --no-cache add npm
    - npm i -g heroku@7.68.0
    - heroku container:login
    - heroku create mini-projet-gitlab-staging-aug || echo "project already exist"
    - heroku container:push -a mini-projet-gitlab-staging-aug web
    - heroku logs -n 100 --app mini-projet-gitlab-staging-aug
    - heroku container:release -a mini-projet-gitlab-staging-aug web

test staging:
  <<: *test
  stage: Test staging
  only:
    - staging
  variables:
    DOMAIN: mini-projet-gitlab-staging-aug-4cf9ddbae0fe.herokuapp.com

deploy review:
  stage: Deploy review
  only:
    - merge_requests
  script:
    - apk --no-cache add npm jq
    - npm i -g heroku@7.68.0
    - heroku container:login
    - APP_NAME=mini-projet-gitlab-$CI_COMMIT_REF_NAME
    - "[[ ${#APP_NAME} -gt 31 ]] && echo 'the name of the heroku application you want to create is longer than 30 characters' && exit 1"
    - heroku create $APP_NAME  || echo "project already exist"
    - heroku container:push -a $APP_NAME web
    - heroku container:release -a $APP_NAME web
    - REVIEW_ENVIRONMENT_URL=$(heroku info $APP_NAME --json | jq -r '.app.web_url')
    - echo "REVIEW_ENVIRONMENT_URL=$REVIEW_ENVIRONMENT_URL" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $REVIEW_ENVIRONMENT_URL
    on_stop: stop review

stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual
  script:
    - apk --no-cache add npm
    - npm i -g heroku@7.68.0
    - heroku container:login
    - heroku apps:destroy -a mini-projet-gitlab-$CI_COMMIT_REF_NAME -c mini-projet-gitlab-$CI_COMMIT_REF_NAME

deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: https://mini-projet-gitlab-prod-aug-91895f21d71e.herokuapp.com/
  only:
    - main
  script:
    - apk --no-cache add npm
    - npm i -g heroku@7.68.0
    - heroku container:login
    - heroku create mini-projet-gitlab-prod-aug  || echo "project already exist"
    - heroku container:push -a mini-projet-gitlab-prod-aug web
    - heroku container:release -a mini-projet-gitlab-prod-aug web

test prod:
  <<: *test
  stage: Test prod
  variables:
    DOMAIN: mini-projet-gitlab-prod-aug-91895f21d71e.herokuapp.com