image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - Build
  - Test acceptation
  - Release image
  - Deploy staging
  - Test staging
  - Deploy review
  - Stop review
  - Deploy prod
  - Test prod

.test_template: &test
  image: alpine
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl "https://$DOMAIN" | grep "Hello world!"

docker-build:
  stage: Build
  script:
    - docker build -t  mini_projet_gitlab .
    - docker save mini_projet_gitlab > mini_projet_gitlab.tar
  artifacts:
    paths:
      - mini_projet_gitlab.tar

test acceptation:
  stage: Test acceptation
  script:
    - docker load < mini_projet_gitlab.tar
    - docker run -d --name webapp mini_projet_gitlab
    - sleep 5
    - apk --no-cache add curl
    - docker ps -a
    - docker exec webapp ls /var/www/html/
    - curl "http://docker:80" | grep  "200"

.release image:
  stage: Release image
  script:
    - docker load < mini_projet_gitlab.tar
    - docker tag mini_projet_gitlab "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag mini_projet_gitlab "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

.deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: https://eazytraining-staging-auget-d12bb760ad6a.herokuapp.com/
  only:
    - master
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create eazytraining-staging-auget || echo "project already exist"
    - heroku container:push -a eazytraining-staging-auget web
    - heroku container:release -a eazytraining-staging-auget web

.deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: https://eazytraining-prod-auget-fb966a39c4c4.herokuapp.com/
  only:
    - master
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create eazytraining-prod-auget  || echo "project already exist"
    - heroku container:push -a eazytraining-prod-auget web
    - heroku container:release -a eazytraining-prod-auget web

.deploy review:
  stage: Deploy review
  only:
    - merge_requests
  script:
    - apk --no-cache add npm jq
    - npm install -g heroku
    - heroku container:login
    - APP_NAME=eazytraining-auget-$CI_COMMIT_REF_NAME
    - "[[ ${#APP_NAME} -gt 31 ]] && echo 'the name of the heroku application you want to create is longer than 30 characters' && exit 1"
    - heroku create $APP_NAME  || echo "project already exist"
    - heroku container:push -a $APP_NAME web
    - heroku container:release -a $APP_NAME web
    - REVIEW_ENVIRONMENT_URL=$(heroku info $APP_NAME --json | jq -r '.app.web_url')
    - echo "REVIEW_ENVIRONMENT_URL=$REVIEW_ENVIRONMENT_URL" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $REVIEW_ENVIRONMENT_URL
    on_stop: stop review

.stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku apps:destroy -a eazytraining-auget-$CI_COMMIT_REF_NAME -c eazytraining-auget-$CI_COMMIT_REF_NAME

.test staging:
  <<: *test
  stage: Test staging
  variables:
    DOMAIN: eazytraining-staging-auget-d12bb760ad6a.herokuapp.com

.test prod:
  <<: *test
  stage: Test prod
  variables:
    DOMAIN: eazytraining-prod-auget-fb966a39c4c4.herokuapp.com